export {
  APP_GITHUB_REPO_URL,
  APP_PRIVACY_HEADLINE,
  APP_PRIVACY_NOTE,
  APP_SLUG,
  APP_TAGLINE,
  APP_TITLE,
  FONT_FAMILY_PREFIX,
  INDEXEDDB_NAME,
  YAML_LINT_SOURCE,
  fontUploadVerifyFamily,
  storageKey,
} from './brand'
export {
  APP_GIT_BRANCH,
  APP_GIT_PR_NUMBER,
  APP_GIT_REVISION,
  APP_HEADER_LEGAL_HTML,
  formatGitBranchLabel,
  formatGitRevisionLabel,
  githubBranchUrl,
  githubCommitUrl,
} from './buildInfo'
export {
  roundTripYaml,
  parseYamlDocument,
  parseYamlPayload,
  serializeYamlPayload,
  validatePayload,
  validateServiceOptions,
  formatZodIssues,
  stripDesignerFields,
  stripDesignerFieldsFromPayload,
  isDesignerOnlyKey,
  DESIGNER_ONLY_FIELDS,
  type PayloadValidationResult,
  elementIndexAtOffset,
  findElementSpans,
  type ElementSpan,
  resolveCursorSelection,
  type CursorSelectionResult,
} from './yaml'
export type { DrawElement } from './schema/elements'
export type { ServiceOptions } from './schema/service'
export {
  colourSchemeToColorMode,
  colorModeToAccent,
  colorModeToColourScheme,
  accentModeToColorMode,
  colorOptionsFromContext,
  isColourSchemeMode,
  isTagColorMode,
  resolveAccentMode,
  resolveColorMode,
  FOUR_COLOR_PALETTE,
  SIX_COLOR_PALETTE,
  type ColourSchemeMode,
  type ColourSchemeValue,
  type TagColorMode,
} from './display/palette'
export {
  clampHexToColorMode,
  clampImageDataToColorMode,
  clampRgbToColorMode,
  imageDataUsesOnlyPaletteColors,
  paletteColorsForMode,
} from './display/palette-clamp'
export {
  DRAW_ELEMENT_TYPES,
  drawElementSchema,
  payloadSchema,
  serviceOptionsSchema,
  PROPERTIES_BY_TYPE,
  BOOLEAN_PROPERTY_KEYS,
  ENUMS,
  getElementTypeCompletions,
  getPropertyCompletions,
  getServiceOptionCompletions,
  getEnumCompletions,
  getElementTypeInsertion,
  getElementTypeInsertionForBlock,
  parseListItemPropertyKeys,
  isDrawElementType,
  applyPlotPropertyUpdate,
  getNestedPropertyValue,
  getPlotNestedPropertyKeys,
  getPropertyDefault,
  getPropertyDescription,
  getPropertyEffectiveValue,
  getPropertySpec,
  getVisibleProperties,
  hasPropertyDefault,
  isPlotNestedProperty,
  isRequiredProperty,
  normalizePropertyValueForStorage,
  PLOT_NESTED_FIELDS,
  REQUIRED_PROPERTIES_BY_TYPE,
  setNestedPropertyValue,
  elementGeometryLocked,
  elementPositionLocked,
  getGeometryProperties,
  getPositionLockProperties,
  getPropertyEditorShape,
  getPropertyEnumValuesForShape,
  ICON_SEQUENCE_ICONS_PREVIEW,
  isPropertyTemplated,
  isTemplateStoredValue,
  POLYGON_POINTS_PREVIEW,
  PLOT_DATA_PREVIEW,
  resolveEditorMode,
  resolveJsonFieldValue,
  TEMPLATE_BOOLEAN_PROPERTIES,
  TEMPLATE_COORDINATE_PROPERTIES,
  TEMPLATE_JSON_PROPERTIES,
  TEMPLATE_NUMBER_PROPERTIES,
  type PropertyEditorMode,
  type PropertyEditorShape,
  type CompletionEntry,
  type CompletionKind,
  type PropertySpecMeta,
} from './schema'
export {
  scanPayloadForAssets,
  collectRequiredFontKeys,
  collectTemplatedFontKeys,
  listLibraryFontKeys,
  scanFontReferences,
  BUNDLED_FONT_KEYS,
  BUNDLED_SHOWCASE_IMAGE_KEY,
  deleteAsset,
  loadAssetsIntoContentMap,
  listContentMapKeys,
  resetContentMap,
  resolveAsset,
  setAsset,
  validateAssetUpload,
  FONT_UPLOAD_ACCEPT,
  guessMimeFromAssetKey,
  isFontMime,
  isImageMime,
  isSupportedFontKey,
  unsupportedFontFormatMessage,
  type AssetEntry,
  type AssetKind,
  type AssetReference,
  type AssetResolution,
  type AssetResolutionStatus,
  type AssetScanResult,
  type AssetUploadResult,
  type FontReference,
} from './assets'
export type { GlyphCoverageIssue } from './renderer'
export {
  scanPayloadForTemplates,
  evaluateTemplate,
  applyTemplateContextToPayload,
  hasTemplateSyntax,
  extractEntityIds,
  extractTemplateExpressions,
  extractAttributeReferences,
  extractVariableReferences,
  type AttributeReference,
  coerceAttributeValue,
  attributeValueEquals,
  TemplateEvaluationError,
  resolvePreviewClockInterval,
  templateNeedsSecondPrecision,
  templateUsesNow,
  type PreviewClockInterval,
  type HaMockContext,
  type TemplateReference,
  type TemplateScanResult,
} from './templates'
export {
  isVisible,
} from './renderer/visibility'
export {
  applyOrderedDitherBuffer,
  finalizeTagImageData,
  mapColor,
  parseColorMarkup,
  stripColorMarkup,
  halftoneTileColors,
  paintOptionsFromContext,
  paintOptionsFromDrawColor,
  renderHalftonePatternDefs,
  resolvePreviewCanvasPaint,
  resolvePreviewPaint,
  resolvePreviewPaintFallback,
  getColorPreviewClampInfo,
  resolveSvgPaint,
  sampleOrderedDitherColor,
  shouldUseHalftonePattern,
  isHalftoneColorName,
  buildArcPiePath,
  arcPieSliceBounds,
  computeOpentypeGlyphPositions,
  fontFamilyNameForKey,
  getCanvasTextDrawStyle,
  normalizeMdiIconName,
  resolveMdiPath,
  createQrModuleGrid,
  qrRenderedSize,
  ICON_DEFAULT_ANCHOR,
  anchorPointFromBox,
  iconSequenceBoxSize,
  isOppositeResizeHandle,
  oppositeResizeHandleForAnchor,
  resolveDirection,
  seSizeFromOppositeHandlePointer,
  renderElement,
  safeRenderElement,
  renderPayload,
  renderLine,
  renderRectangle,
  renderCircle,
  renderText,
  renderMultiline,
  renderRectanglePattern,
  renderPolygon,
  renderEllipse,
  renderArc,
  renderIcon,
  renderIconSequence,
  renderDlimg,
  renderQrcode,
  renderPlot,
  renderProgressBar,
  renderDebugGrid,
  DEBUG_GRID_MIN_SPACING,
  resolveCoordinate,
  resolveX,
  resolveY,
  isNumericStringCoordinate,
  isPercentageCoordinate,
  clearFontRegistry,
  DEFAULT_FONT_KEY,
  getFont,
  parseFont,
  registerFont,
  unregisterFont,
  layoutTextBlock,
  measureTextWidth,
  findMissingCharacters,
  formatMissingCharacterSample,
  scanGlyphCoverageIssues,
  type AccentMode,
  type DitherMode,
  type RenderContext,
  type RenderResult,
  type RenderPrimitive,
  type SvgPrimitive,
  type CanvasPrimitive,
  type CanvasPlotPrimitive,
  type PlotSeriesPrimitive,
  type TextDrawLine,
  type CanvasTextDrawStyle,
  type OpentypeGlyphPosition,
  type QrModuleGrid,
} from './renderer'
