export {
  roundTripYaml,
  parseYamlDocument,
  parseYamlPayload,
  serializeYamlPayload,
  validatePayload,
  validateServiceOptions,
  formatZodIssues,
  stripDesignerFields,
  stripDesignerFieldsFromPayload,
  isDesignerOnlyKey,
  DESIGNER_ONLY_FIELDS,
  type PayloadValidationResult,
} from './yaml'
export type { DrawElement } from './schema/elements'
export type { ServiceOptions } from './schema/service'
export {
  DRAW_ELEMENT_TYPES,
  drawElementSchema,
  payloadSchema,
  serviceOptionsSchema,
  PROPERTIES_BY_TYPE,
  ENUMS,
  getElementTypeCompletions,
  getPropertyCompletions,
  getServiceOptionCompletions,
  getEnumCompletions,
  getElementTypeInsertion,
  getElementTypeInsertionForBlock,
  parseListItemPropertyKeys,
  isDrawElementType,
  getPropertyDefault,
  getPropertyDescription,
  getPropertyEffectiveValue,
  getPropertySpec,
  getVisibleProperties,
  hasPropertyDefault,
  isRequiredProperty,
  normalizePropertyValueForStorage,
  REQUIRED_PROPERTIES_BY_TYPE,
  type CompletionEntry,
  type CompletionKind,
  type PropertySpecMeta,
} from './schema'
export {
  scanPayloadForAssets,
  BUNDLED_FONT_KEYS,
  deleteAsset,
  loadAssetsIntoContentMap,
  listContentMapKeys,
  resetContentMap,
  resolveAsset,
  setAsset,
  validateAssetUpload,
  guessMimeFromAssetKey,
  isFontMime,
  isImageMime,
  type AssetEntry,
  type AssetKind,
  type AssetReference,
  type AssetResolution,
  type AssetResolutionStatus,
  type AssetScanResult,
  type AssetUploadResult,
} from './assets'
export {
  scanPayloadForTemplates,
  evaluateTemplate,
  applyTemplateContextToPayload,
  hasTemplateSyntax,
  extractEntityIds,
  extractTemplateExpressions,
  TemplateEvaluationError,
  type HaMockContext,
  type TemplateReference,
  type TemplateScanResult,
} from './templates'
export {
  mapColor,
  renderElement,
  renderPayload,
  renderLine,
  renderRectangle,
  renderCircle,
  renderText,
  renderMultiline,
  renderRectanglePattern,
  renderPolygon,
  renderEllipse,
  renderArc,
  renderIcon,
  renderIconSequence,
  renderDlimg,
  renderQrcode,
  renderPlot,
  renderProgressBar,
  renderDebugGrid,
  resolveCoordinate,
  resolveX,
  resolveY,
  type AccentMode,
  type RenderContext,
  type RenderResult,
  type RenderPrimitive,
  type SvgPrimitive,
  type CanvasPrimitive,
} from './renderer'
