export {
  roundTripYaml,
  parseYamlDocument,
  parseYamlPayload,
  serializeYamlPayload,
  validatePayload,
  validateServiceOptions,
  formatZodIssues,
  stripDesignerFields,
  stripDesignerFieldsFromPayload,
  isDesignerOnlyKey,
  DESIGNER_ONLY_FIELDS,
  type PayloadValidationResult,
} from './yaml'
export type { DrawElement } from './schema/elements'
export type { ServiceOptions } from './schema/service'
export {
  DRAW_ELEMENT_TYPES,
  drawElementSchema,
  payloadSchema,
  serviceOptionsSchema,
  PROPERTIES_BY_TYPE,
  ENUMS,
  getElementTypeCompletions,
  getPropertyCompletions,
  getServiceOptionCompletions,
  getEnumCompletions,
  getElementTypeInsertion,
  getElementTypeInsertionForBlock,
  parseListItemPropertyKeys,
  isDrawElementType,
  applyPlotPropertyUpdate,
  getNestedPropertyValue,
  getPlotNestedPropertyKeys,
  getPropertyDefault,
  getPropertyDescription,
  getPropertyEffectiveValue,
  getPropertySpec,
  getVisibleProperties,
  hasPropertyDefault,
  isPlotNestedProperty,
  isRequiredProperty,
  normalizePropertyValueForStorage,
  PLOT_NESTED_FIELDS,
  REQUIRED_PROPERTIES_BY_TYPE,
  setNestedPropertyValue,
  type CompletionEntry,
  type CompletionKind,
  type PropertySpecMeta,
} from './schema'
export {
  scanPayloadForAssets,
  collectRequiredFontKeys,
  collectTemplatedFontKeys,
  listLibraryFontKeys,
  scanFontReferences,
  BUNDLED_FONT_KEYS,
  deleteAsset,
  loadAssetsIntoContentMap,
  listContentMapKeys,
  resetContentMap,
  resolveAsset,
  setAsset,
  validateAssetUpload,
  FONT_UPLOAD_ACCEPT,
  guessMimeFromAssetKey,
  isFontMime,
  isImageMime,
  isSupportedFontKey,
  unsupportedFontFormatMessage,
  type AssetEntry,
  type AssetKind,
  type AssetReference,
  type AssetResolution,
  type AssetResolutionStatus,
  type AssetScanResult,
  type AssetUploadResult,
  type FontReference,
} from './assets'
export type { GlyphCoverageIssue } from './renderer'
export {
  scanPayloadForTemplates,
  evaluateTemplate,
  applyTemplateContextToPayload,
  hasTemplateSyntax,
  extractEntityIds,
  extractTemplateExpressions,
  TemplateEvaluationError,
  type HaMockContext,
  type TemplateReference,
  type TemplateScanResult,
} from './templates'
export {
  mapColor,
  parseColorMarkup,
  stripColorMarkup,
  halftoneTileColors,
  sampleOrderedDitherColor,
  shouldUseHalftonePattern,
  isHalftoneColorName,
  buildArcPiePath,
  arcPieSliceBounds,
  computeOpentypeGlyphPositions,
  fontFamilyNameForKey,
  getCanvasTextDrawStyle,
  normalizeMdiIconName,
  resolveMdiPath,
  createQrModuleGrid,
  qrRenderedSize,
  ICON_DEFAULT_ANCHOR,
  anchorPointFromBox,
  iconSequenceBoxSize,
  isOppositeResizeHandle,
  oppositeResizeHandleForAnchor,
  resolveDirection,
  seSizeFromOppositeHandlePointer,
  renderElement,
  renderPayload,
  renderLine,
  renderRectangle,
  renderCircle,
  renderText,
  renderMultiline,
  renderRectanglePattern,
  renderPolygon,
  renderEllipse,
  renderArc,
  renderIcon,
  renderIconSequence,
  renderDlimg,
  renderQrcode,
  renderPlot,
  renderProgressBar,
  renderDebugGrid,
  resolveCoordinate,
  resolveX,
  resolveY,
  isNumericStringCoordinate,
  isPercentageCoordinate,
  clearFontRegistry,
  DEFAULT_FONT_KEY,
  getFont,
  parseFont,
  registerFont,
  unregisterFont,
  layoutTextBlock,
  measureTextWidth,
  findMissingCharacters,
  formatMissingCharacterSample,
  scanGlyphCoverageIssues,
  type AccentMode,
  type DitherMode,
  type RenderContext,
  type RenderResult,
  type RenderPrimitive,
  type SvgPrimitive,
  type CanvasPrimitive,
  type CanvasPlotPrimitive,
  type PlotSeriesPrimitive,
  type TextDrawLine,
  type CanvasTextDrawStyle,
  type OpentypeGlyphPosition,
  type QrModuleGrid,
} from './renderer'
