import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Third-party license inventory for bundled npm dependencies (issue #103),
 * shipped as the `THIRD_PARTY.md` release asset and inside the npm package.
 * NOT a heavyweight scanner — package.json license fields suffice; fails
 * loudly on a missing license field (AGENTS.md, "fail early and loudly").
 *
 * The dependency list is derived from package.json's own "dependencies" map
 * rather than hardcoded: `vite.lib.config.ts` bundles every runtime
 * dependency into the single self-contained ESM (no code splitting, no
 * externals — docs/bundle-audit.md), so "dependencies" already IS the exact
 * set of packages compiled into the artifact.
 */

export interface DependencyLicenseInfo {
  name: string
  version: string
  license: string
  link?: string
}

/** Sorted dependency names — the actual bundle composition, not a hand list. */
export function bundledDependencyNames(packageJson: { dependencies?: Record<string, string> }): string[] {
  return Object.keys(packageJson.dependencies ?? {}).sort()
}

function readInstalledPackageJson(name: string, nodeModulesDir: string): Record<string, unknown> {
  const path = join(nodeModulesDir, name, 'package.json')
  let raw: string
  try {
    raw = readFileSync(path, 'utf8')
  } catch (error) {
    throw new Error(
      `Cannot read installed package.json for "${name}" at ${path} — is it installed? (${(error as Error).message})`,
      { cause: error },
    )
  }
  return JSON.parse(raw) as Record<string, unknown>
}

/**
 * Reads name/version/license/link for one installed dependency from its
 * `node_modules/<name>/package.json`. Throws loudly when the license field
 * is missing — no silent "unknown license" fallback.
 */
export function readDependencyLicenseInfo(name: string, nodeModulesDir: string): DependencyLicenseInfo {
  const pkg = readInstalledPackageJson(name, nodeModulesDir)
  const license = pkg.license
  if (typeof license !== 'string' || license.trim().length === 0) {
    throw new Error(
      `Package "${name}"@${String(pkg.version)} has no "license" field in its package.json — ` +
        'cannot generate THIRD_PARTY.md without one (fail loudly, no "unknown" fallback)',
    )
  }
  const homepage = typeof pkg.homepage === 'string' ? pkg.homepage : undefined
  const repositoryUrl =
    typeof pkg.repository === 'object' && pkg.repository !== null && 'url' in pkg.repository
      ? String((pkg.repository as { url?: unknown }).url)
      : undefined
  return {
    name,
    version: String(pkg.version),
    license,
    link: homepage ?? repositoryUrl,
  }
}

/** License info for every named bundled dependency, sorted by name. */
export function collectBundledDependencyInfo(names: string[], nodeModulesDir: string): DependencyLicenseInfo[] {
  return [...names]
    .sort()
    .map((name) => readDependencyLicenseInfo(name, nodeModulesDir))
}

const DOCS_THIRD_PARTY_URL =
  'https://github.com/schlomo/odl-drawcustom-designer/blob/main/docs/THIRD_PARTY.md'

/**
 * Renders the bundled-dependency license table as markdown. Pure formatting
 * — no filesystem access — so it's fully unit-tested independent of what's
 * actually installed.
 */
export function generateThirdPartyMarkdown(deps: DependencyLicenseInfo[]): string {
  const rows = deps
    .map((dep) => `| ${dep.name} | ${dep.version} | ${dep.license} | ${dep.link ?? ''} |`)
    .join('\n')
  return `# Third-party notices (bundled dependencies)

Auto-generated by \`tools/thirdPartyNotices.ts\` for the odl-drawcustom-designer
library build — every package listed here is compiled into the single
\`odl-drawcustom-designer.js\` ESM. For the repository's broader attribution
(vendored docs, fonts, non-bundled upstream ecosystems) see
[\`docs/THIRD_PARTY.md\`](${DOCS_THIRD_PARTY_URL}).

| Package | Version | License | Link |
|---|---|---|---|
${rows}
`
}
